services:
  app:
    container_name: medfabric_app
    build: 
      context: .
      dockerfile: app.Dockerfile
    ports: 
      - "8501:8501"
    depends_on:
      - db
#        condition: service_healthy
#        restart: true
    volumes:
      - ./:/app
      - ./medfabric:/app/medfabric:ro
      - ./public_data:/app/public_data   
  db:
    container_name: medfabric_db
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: medfabric_pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

#  tailscale:
#    image: tailscale/tailscale:latest
#    container_name: medfabric_tailscale
#    network_mode: "host"
#    cap_add:
#      - NET_ADMIN
#      - SYS_MODULE
#    volumes:
#      - tailscale:/var/lib/tailscale
#    command: tailscaled

volumes:
  db_data:
  pgadmin_data:
#  tailscale: