[about]
name = "MedFabric"
version = "3.0.0-release"
description = "ASPECTS annotation platform for ischemic stroke imaging research."
creator = "Nguyễn Đức Hùng"
institution = "iBME Lab, Hanoi University of Science and Technology, dataset provided by E Hospital"
contact_email = ""
project_url = ""
